name: Build Android for store

on:
  workflow_dispatch: {}

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        # Update to Node.js 20
        env:
          node-version: '20.x'

      - uses: actions/cache@v2
        with:
          path: path/to/your/project/Library
          key: Library-UnityAndroid
          restore-keys: |
            Library-Unity-
            Library-
        # Update to Node.js 20
        env:
          node-version: '20.x'

      - name: Activate Unity License
        run: |
          mkdir -p $HOME/.local/share/unity3d/Unity/
          echo "$UNITY_LICENSE" > $HOME/.local/share/unity3d/Unity/Unity_lic.ulf

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          node-version: '20.x'
        with:
          targetPlatform: Android 
          androidAppBundle: 'true'
        # Update to Node.js 20
       
          

      - uses: actions/upload-artifact@v2
        with:
          name: Build-Android
          path: build/Android
        # Update to Node.js 20
        env:
          node-version: '20.x'
