name: Build Android for store

on:
  workflow_dispatch: {}

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Add other necessary steps (e.g., caching, activating Unity license)

      - name: Copy artifacts
        run: |
          mkdir -p $HOME/build-artifacts
          # Replace 'path/to/your/artifacts' with the actual path to your artifacts directory
          cp -r path/to/your/artifacts/* $HOME/build-artifacts

      - uses: actions/upload-artifact@v2
        with:
          name: Build-Android
          path: $HOME/build-artifacts
